services:
  nginx:
    build: ./requirements/nginx
    image: inception/ngnix
    container_name: nginx
    depends_on:
      - "wordpress"
    ports: 
      - "443:443"
    networks:
      - inception
    volumes:
      - wp:/var/www/wp
  wordpress:
    build: ./requirements/wordpress
    image: inception/wordpress
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - "mysql"
    networks:
      - inception
    volumes:
      - wp:/var/www/wp
  mysql:
    build: 
      context: ./requirements/mysql
      args:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
    image: inception/mysql
    container_name: mysql
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mysql:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  mysql:
    name: mysql
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USERNAME}/data/mysql
  wp:
    name: wp
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USERNAME}/data/wp
