version: "3.5"
services:
  nginx:
    build: ./requirements/nginx
    image: inception/ngnix
    container_name: nginx
    depends_on:
      - "wordpress"
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress
      args:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
        WP_ADMIN_NAME: ${WP_ADMIN_NAME}
        WP_ADMIN_PASS: ${WP_ADMIN_PASS}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_USER_NAME: ${WP_USER_NAME}
        WP_USER_PASS: ${WP_USER_PASS}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
    image: inception/wordpress
    container_name: wordpress
    depends_on:
      - "mysql"
    networks:
      - inception
    volumes:
      - wp:/var/www/html
    restart: always
  mysql:
    build:
      context: ./requirements/mysql
      args:
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_NAME: ${DB_NAME}
    image: inception/mysql
    container_name: mysql
    networks:
      - inception
    volumes:
      - mysql:/var/lib/mysql
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  mysql:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/mysql
  wp:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/data/wp
