CREATE DATABASE IF NOT EXISTS DB_NAME DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT ALL ON DB_NAME.* TO 'DB_USER'@'localhost' IDENTIFIED BY 'DB_PASS';
GRANT ALL ON DB_NAME.* TO 'DB_USER'@'%' IDENTIFIED BY 'DB_PASS';

FLUSH PRIVILEGES;

GRANT ALL ON DB_NAME.* TO 'root'@'localhost' IDENTIFIED BY 'DB_ROOT_PASS';
GRANT ALL ON DB_NAME.* TO 'root'@'%' IDENTIFIED BY 'DB_ROOT_PASS';

-- ALTER USER 'root'@'localhost' IDENTIFIED BY 'DB_ROOT_PASS';
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('DB_ROOT_PASS');
SET PASSWORD FOR 'root'@'%'=PASSWORD('DB_ROOT_PASS');

FLUSH PRIVILEGES;
